---
- name: Setup ZSH
  ansible.builtin.include_tasks: zsh.yml
  when: shell == "zsh"

- name: Setup Bash
  ansible.builtin.include_tasks: bash.yml
  when: shell == "bash"

- name: Ensure local bin directory exists
  ansible.builtin.file:
    path: "/home/{{ user }}/.local/bin"
    state: directory
    owner: "{{ user }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: "0755"
  become: true

- name: Install Oh My Posh if not present
  ansible.builtin.shell: |
    if [ ! -f "/home/{{ user }}/.local/bin/oh-my-posh" ]; then
      set -o pipefail
      curl -s https://ohmyposh.dev/install.sh | bash -s -- -d /home/{{ user }}/.local/bin/
      if [ $? -eq 0 ]; then
        echo "changed=True comment='Oh My Posh installed successfully.'"
      else
        echo "failed=True comment='Installation failed.'"
        exit 1
      fi
    else
      echo "changed=False comment='Oh My Posh is already installed.'"
    fi
  register: oh_my_posh_installation
  become: true
  become_user: "{{ user }}"
  when: oh_my_posh | bool
  changed_when: "'changed=True' in oh_my_posh_installation.stdout"
  failed_when: "'failed=True' in oh_my_posh_installation.stdout"
  check_mode: false

- name: Create Oh My Posh themes directory
  ansible.builtin.file:
    path: "/home/{{ user }}/.config/oh-my-posh/themes"
    state: directory
    owner: "{{ user }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: "0755"
  become: true
  when: oh_my_posh | bool

- name: Copy Oh My Posh theme file to themes directory
  ansible.builtin.copy:
    src: "infinite.omp.yml"
    dest: "/home/{{ user }}/.config/oh-my-posh/themes/infinite.omp.yml"
    owner: "{{ user }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: "0644"
  become: true
  when: oh_my_posh | bool
