---
- name: Install zsh
  ansible.builtin.package:
    name: zsh
    state: present
  become: true

- name: Set zsh as the default shell for the user
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /usr/bin/zsh
  become: true
  become_user: root
  when: shell == "zsh"

- name: Deploy .zshrc files to user's home
  ansible.builtin.copy:
    src: .zshrc
    dest: "~/.zshrc"
    owner: "{{ user }}"
    mode: "0644"
  become: true
  become_user: "{{ user }}"

- name: Ensure pacman hook directory exists
  ansible.builtin.file:
    path: "/etc/pacman.d/hooks"
    state: directory
    owner: root
    mode: "0755"
  become: true
  become_user: root
  when: package_manager == "pacman"

- name: Add pacman hook to update zsh completions
  ansible.builtin.copy:
    src: zsh-rehash.hook
    dest: "/etc/pacman.d/hooks/zsh-rehash.hook"
    owner: root
    mode: "0644"
  become: true
  become_user: root
  when: package_manager == "pacman"

- name: Add systemd service to update Pacman File Database
  ansible.builtin.copy:
    src: pacman-refresh-file-db.service
    dest: "/etc/systemd/system/pacman-refresh-file-db.service"
    owner: root
    mode: "0644"
  become: true
  become_user: root
  notify: Start pacman-refresh-file-db.service
  when: package_manager == "pacman"

- name: Add systemd timer to update Pacman File Database
  ansible.builtin.copy:
    src: pacman-refresh-file-db.timer
    dest: "/etc/systemd/system/pacman-refresh-file-db.timer"
    owner: root
    mode: "0644"
  become: true
  become_user: root
  notify: Enable pacman-refresh-file-db.timer
  when: package_manager == "pacman"

- name: Deploy .profile for zsh to user's home
  ansible.builtin.template:
    src: .profile.j2
    dest: "~/.zprofile"
    owner: "{{ user }}"
    mode: "0644"
  become: true
  become_user: "{{ user }}"
